controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
fetch_weather:
    path: /fetch-weather
    controller: App\Controller\WeatherController::getWeatherData